repo: https://github.com/chainreactors/picker
proxy:
  url: 'http://127.0.0.1:7890'
  rss: false
  bot: false
rss:
  CustomRSS:
    enabled: true
    filename: CustomRSS.opml
  Subscriptions-OnMyMac:
    enabled: true
    filename: Subscriptions-OnMyMac.opml
  CyberSecurityRSS:
    enabled: false
    url: >-
      https://github.com/chainreactors/picker/raw/master/rss/CyberSecurityRSS.opml
    filename: CyberSecurityRSS.opml
  CyberSecurityRSS-tiny:
    enabled: false
    url: https://github.com/chainreactors/picker/raw/master/rss/CyberSecurityRSS-tiny.opml
    filename: CyberSecurityRSS-tiny.opml
  Chinese-Security-RSS:
    enabled: false
    url: >-
      https://github.com/chainreactors/picker/raw/master/rss/Chinese-Security-RSS.opml
    filename: Chinese-Security-RSS.opml
  awesome-security-feed:
    enabled: false
    url: >-
      https://github.com/chainreactors/picker/raw/master/rss/awesome-security-feed.opml
    filename: awesome-security-feed.opml
  SecurityRSS:
    enabled: false
    url: 'https://github.com/Han0nly/SecurityRSS/blob/master/SecureRss.opml'
    filename: SecureRss.opml
  wechatRSS:
    enabled: false
    url: 'https://wechat2rss.xlab.app/opml/sec.opml'
    filename: wechatRSS.opml
  chinese-independent-blogs:
    enabled: false
    url: >-
      https://raw.githubusercontent.com/timqian/chinese-independent-blogs/master/feed.opml
    filename: chinese-independent-blogs.opml
bot:
  feishu:
    enabled: false
    secrets: FEISHU_KEY
    key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  wecom:
    enabled: false
    secrets: WECOM_KEY
    key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  dingtalk:
    enabled: true
    secrets: DINGTALK_KEY
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  qq:
    enabled: false
    secrets: QQ_KEY
    qq_id: '2419110059'
    group_id:
      - '808542982'
      - '217863340'
    key: xxxxxxxxxx
  telegram:
    enabled: false
    secrets: TELEGRAM_KEY
    chat_id:
      - '-799557100'
    key: xxxxxxxxxx
  mail:
    enabled: false
    secrets: MAIL_KEY
    secrets_receiver: MAIL_RECEIVER
    address: firmianay@163.com
    server: smtp.163.com
    from: security-bot <yangchao@lixiang.com>
    receiver: 'a@163.com,b@163.com'
    key: xxxxxxxxxx
pick_bot:
  dingtalk:
    enabled: false
    secrets: DINGTALK_KEY
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  feishu:
    enabled: true
    secrets: FEISHU_KEY
    key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx